config/routes.rb
ContractBuilder::Application.routes.draw do
  get "welcome/index"

  root 'welcome#index'
  

  resources :contracts

end

app/models/contract.rb
class Contract < ActiveRecord::Base
    validates :compName, presence: true
end

app/models/create.rb
class Create < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
    http_basic_authenticate_with name: "anthony", password: "1234"
    def new
        @contract = Contract.new
    end
    def create
        @contract = Contract.new(contract_params)
        if @contract.save
            redirect_to @contract
        else
            render 'new'
        end
    end
    
    def show
        @contract = Contract.find(params[:id])
    end
    
    def index
        @contract = Contract.all
    end
    
    def edit
        @contract = Contract.find(params[:id])
    end
    
    def update
        @contract = Contract.find(params[:id])
        if @contract.update(params[:contract].permit(:compName, :accountNum, :compPhone, :compFax, :shipStr, :shipCity, :shipSt, :shipZip, :shipCounty, :shipTax,:billShipChk, :billStr, :billCity, :billSt, :billZip, :billCounty, :billTax))
            redirect_to @contract
        else
            render 'edit'
        end
    end
    def destroy
        @contract = Contract.find(params[:id])
        @contract.destroy
        
        redirect_to contracts_path
    end
    private
        def contract_params
            params.require(:contract).permit(:compName, :accountNum, :compPhone, :compFax, :shipStr, :shipCity, :shipSt, :shipZip, :shipCounty, :shipTax,:billShipChk, :billStr, :billCity, :billSt, :billZip, :billCounty, :billTax)
        end
        
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contracts/_form.html.erb
<%= form_for @contract do |f| %>
      <% if @contract.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contract.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @contract.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <% end %>
  </div>

    <h2>About You</h2>
    
    <table>
    <tr>
        <td>Company Name: </td>
        <td><%= f.text_field :compName %></td>
        <td><div class="table_head">Owner or Admin Contact: </div></td>
        <td><%= text_field_tag(:adminContact)%></td>
        <td><div class = "table_head">Computer/Hardware Contact: </td>
        <td><%= text_field_tag(:hard_contact)%></td>
    </tr>
    <tr>
        <td>Account Number: </td>
        <td><%= f.text_field :accountNum %></td>
        <td>Contact Phone: </td>
        <td><%= text_field_tag(:admin_phone)%></td>
        <td>Contact Phone: </td>
        <td><%= text_field_tag(:hard_phone)%></td>
    </tr>
    <tr>
        <td>Company Phone: </td>
        <td><%= f.text_field :compPhone %></td>
        <td>Contact Email: </td>
        <td><%= text_field_tag(:admin_email)%></td>
        <td>Contact Email: </td>
        <td><%= text_field_tag(:hard_email)%></td>
    </tr>
    <tr>
        <td>Company Fax: </td>
        <td><%= f.text_field :compFax %></td>
    </tr>
    </table>
    
   <h2>Shipping Address</h2>
  <table>
    <tr>
        <td>Street: </td>
        <td><%= f.text_field :shipStr %></td>
        <td>County: </td>
        <td><%= f.text_field(:shipCounty)%></td>
    </tr>
    <tr>
        <td>City: </td>
        <td><%= f.text_field :shipCity %></td>
        <td>Sales Tax Rate: </td>
        <td><%= f.text_field(:shipTax)%></td>
    </tr>
    <tr>
        <td>State: </td>
        <td><%= f.text_field(:shipSt)%></td>
    </tr>
    <tr>
        <td>Zip Code: </td>
        <td><%= f.text_field(:shipZip) %></td>
    </tr>
    
    
    
  </table>
  <h2>Billing Address</h2>
  <p>
    <%= f.label(:billShipChkLbl, "Same as Shipping Address")%>
    <%= f.check_box(:billShipChk)%>
  </p>
  <table>
    <tr>
        <td>Street: </td>
        <td><%= f.text_field :billStr %></td>
        <td>County: </td>
        <td><%= f.text_field(:billCounty)%></td>
    </tr>
    <tr>
        <td>City: </td>
        <td><%= f.text_field :billCity %></td>
        <td>Sales Tax Rate: </td>
        <td><%= f.text_field(:billTax)%></td>
    </tr>
    <tr>
        <td>State: </td>
        <td><%= f.text_field(:billSt)%></td>
    </tr>
    <tr>
        <td>Zip Code: </td>
        <td><%= f.text_field(:billZip) %></td>
    </tr>
  </table>
  
  <h2>How did you become aware of our services?</h2>
    <table cellspacing="0">
        <tr>
            <td>Magazine: <%= check_box_tag(:magazineChk)%> </td>
            <td>Trade Show: <%= check_box_tag(:tradeShowChk)%></td>
            <td>Friend: <%= check_box_tag(:friendChk)%></td>
            <td>Direct Mail: <%= check_box_tag(:friendChk)%></td>
            <td>Internet: <%= check_box_tag(:internetChk)%></td>
        </tr>
    </table>
    <table>
        <tr>
            <td>Sales Person: <%= text_field_tag(:salesPersTxt)%></td>
            <td>Referral: <%= text_field_tag(:referralTxt)%></td>
            <td>Other: <%= text_field_tag(:otherTxt)%></td>
        </tr>
    </table>
  <h2>Memberships</h2><p><div class="hint_text">(Select all desired to be displayed on Car-Part.com)</div></p>
  <table>
    <tr>
        <td>ARA: </td>
        <td><%= check_box_tag(:araChk)%> </td>
        <td>URG: </td>
        <td><%= check_box_tag(:urgChk) %></td>
        <td>URG 8000: </td>
        <td><%= check_box_tag(:urg8000Chk)%></td>
    </tr>
    <tr>
        <td>CARS: </td>
        <td><%= check_box_tag(:carsChk)%></td>
        <td>URG 6000: </td>
        <td><%= check_box_tag(:urg6000Chk)%></td>
    </tr>
    <tr>
        <td>Gold Seal: </td>
        <td><%= check_box_tag(:goldSealChk)%></td>
        <td>URG 7000: </td>
        <td><%= check_box_tag(:urg7000Chk)%></td>
        
    </tr>
  </table>
  <table>
    <tr>
        <td>State Organization: <%= text_field_tag(:stateOrg)%></td>
        <td>Local Organization: <%= text_field_tag(:localOrg)%></td>
    </tr>
  </table>
  
  <table>
    <tr>
        <td>None Displayed: <%= check_box_tag(:noMemChk)%></td>
    </tr>
  </table>
  <h2>Current Inventory Management System</h2>
  <select name="city_id" id="city_id">
    <option value="1">Internet Checkmate</option>
    <option value="2">Telnet Checkmate</option>
    <option value="3">Fast Parts</option>
    <option value="4">Pinnacle Classic</option>
    <option value="5">Pinnacle Pro</option>
    <option value="6">AIM</option>
    <option value="7">iSoft</option>
    <option value="8">Hollander</option>
    <option value="9">Powerlink</option>
    <option value="10">Powerlink II</option>
    <option value="11">Powerlink II w/Hollander PowerStation</option>
    <option value="12">Other</option>
    <option value="13">None</option>
    
  </select>
  
  <table>
    <tr>
        <td>Other: <%= text_field_tag(:otherIMS)%></td>
    </tr>
    <tr>
        <td>None: <%= check_box_tag(:noIMSChk)%></td>
    </tr>
  </table>
    <br>
      <%= f.submit 'Submit Contract', :class => 'submit_button' %>
  <script>
    
    $("button").on("click", function() {
      alert("clicked!")
    });
  </script>
<% end %>
<br>

app/views/contracts/_form_shipping.html.erb
<%= form_for @contract do |f| %>
      <% if @contract.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@contract.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @contract.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
    <% end %>
  </div>
  
  <h2>Shipping Address</h2>
  <p>
    <%= f.label(:shipStLbl, "Street")%>
    <%= f.text_field :shipStr %><br>
    <%= f.label(:shipCityLbl, "City")%>
    <%= f.text_field :shipCity %>
    <%= f.label(:shipStLbl, "State")%>
    <%= f.text_field(:shipSt)%>
    <%= f.label(:shipZipLbl, "Zip")%>
    <%= f.text_field(:shipZip) %><br>
    <%= f.label(:shipCountyLbl, "County")%>
    <%= f.text_field(:shipCounty)%>
    <%= f.label(:shipTaxLbl, "Sales Tax Rate")%>
    <%= f.text_field(:shipTax)%>
  </p>
  <h2>Billing Address</h2>
  <p>
    <%= f.label(:billShipChkLbl, "Same as Shipping Address")%>
    <%= check_box_tag(:billShipChk)%>
  </p>
  <p>
    <%= f.label(:billStLbl, "Street")%>
    <%= f.text_field :billStr %><br>
    <%= f.label(:billCityLbl, "City")%>
    <%= f.text_field :billCity %>
    <%= f.label(:billStLbl, "State")%>
    <%= f.text_field(:billSt)%>
    <%= f.label(:billZipLbl, "Zip")%>
    <%= f.text_field(:billZip) %><br>
    <%= f.label(:billCountyLbl, "County")%>
    <%= f.text_field(:billCounty)%>
    <%= f.label(:billTaxLbl, "Sales Tax Rate")%>
    <%= f.text_field(:billTax)%>
  </p>
  
<% end %>

app/views/contracts/edit.html.erb
<%= stylesheet_link_tag "new_style_sheet.css" %>

<header>
    <a href="http://imgur.com/qYhF7gF"><img src="http://i.imgur.com/Zt6y8Mr.jpg"/></a>
    <h1>Contract for <%=@contract.compName%></h1>
    <div class="top_nav">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Contract List', contracts_path %>
      </div>
  </header>
<%= render 'form' %>

<div class = "footer">
<br>
<br>
<br>
    <div class="bottom_nav" ><%= link_to 'Back to Home', root_path %>
    <%= link_to 'Contract List', contracts_path %>
    </div>
    
<br>
</div>

app/views/contracts/index.html.erb
<%= stylesheet_link_tag "index_style_sheet.css" %>
<h1>Contract List</h1>
 
<table cellpadding="10">
  <tr>
    <td><b>Company Name</b></td>
    <td><b>Account Number</b></td>
  </tr>
  <% @contract.each do |contract| %>
    <tr>
      <td><%= contract.compName %></td>
      <td><%= contract.accountNum %></td>
      <td><%= link_to 'Show', contract %></td>
    <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
    <td><%= link_to 'Destroy', contract_path(contract),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'Back to Home', root_path %>

app/views/contracts/new.html.erb
<head>
    
</head>
<body>
<%= stylesheet_link_tag "new_style_sheet.css" %>
    <header>
    <a href="http://imgur.com/qYhF7gF"><img src="http://i.imgur.com/Zt6y8Mr.jpg"/></a>
    
    <div class="top_nav">
      <%= link_to 'Home', root_path %>
      <%= link_to 'Contract List', contracts_path %>
      <%= link_to 'FAQ', "#"%>
      <%= link_to 'About', "#"%>
      <%= link_to 'Help', "#"%>
      </div>
      <br></br>
  </header>
<h1>New Contract</h1>
<%= render 'form' %>
<div class = "footer">
<br>
<br>
<br>
    <div class="bottom_nav" ><%= link_to 'Home', root_path %>
    <%= link_to 'Contract List', contracts_path %>
    </div>
    
<br>
</div>
</body>

app/views/contracts/show.html.erb
<p>
    <strong>Company Name: </strong>
    <%= @contract.compName %><br>
    <strong>Account Number: </strong>
    <%= @contract.accountNum %><br>
    <strong>Company Phone Number: </strong>
    <%= @contract.compPhone %><br>
    <strong>Company Fax Number: </strong>  
    <%= @contract.compFax %><br>
    <strong>Bill/Ship Same?: </strong>
    <%= @contract.billShipChk %>

</p>

<%= link_to 'View Contract List', contracts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContractBuilder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/_form_search.html.erb
<%= form_for @searchQuery do |f| %>
    <p>Account Number: <%= text_field_tag(:searchQuery)%></p>
<%= f.submit %>
<% end %>

app/views/welcome/index.html.erb
<head>
    
</head>
<body>
<%= stylesheet_link_tag "new_style_sheet.css" %>
    <header>
        <a href="http://imgur.com/qYhF7gF"><img src="http://i.imgur.com/Zt6y8Mr.jpg"/></a>
    
    <div class="top_nav">
      <%= link_to 'Home', root_path %>
      <%= link_to 'New Contract', new_contract_path%>
      <%= link_to 'Contract List', contracts_path %>
      <%= link_to 'FAQ', "#"%>
      <%= link_to 'About', "#"%>
      <%= link_to 'Help', "#"%>
      </div>
      <br></br>
  </header>

<div class = "footer">
<br>
<br>
<br>
    <div class="bottom_nav" ><%= link_to 'Home', root_path %>
    <%= link_to 'Contract List', contracts_path %>
    </div>
    
<br>
</div>
</body>